---

- name: Enable daily documents-backup
  ansible.builtin.file:
    src: /etc/oxiscripts/jobs/backup-documents.sh
    dest: /etc/cron.daily/backup-documents
    owner: root
    group: root
    state: link

- name: Enable daily backup-cleanup
  ansible.builtin.file:
    src: /etc/oxiscripts/jobs/backup-cleanup.sh
    dest: /etc/cron.daily/backup-Z98-cleanup
    owner: root
    group: root
    state: link

- name: Enable daily rsync-backup
  ansible.builtin.file:
    src: /etc/oxiscripts/jobs/backup-rsync.sh
    dest: /etc/cron.daily/backup-Z99-rsync
    owner: root
    group: root
    state: link
